### ISSUE TITLE
unable to access 'https://github.com/openshift/ruby-ex.git/': Failed connect to github.com:443; No route to host

### ISSUE THREAD

**Issue by kumarranja** [openshift/ruby-ex#19]
Hi,

while deploying an ruby-ex application in openshift 1.5 i am getting the below error :- 

[root@master demo]# oc logs ruby-ex
[ruby-ex.log](https://github.com/openshift/ruby-ex/files/1702098/ruby-ex.log)
-build
Cloning "https://github.com/openshift/ruby-ex.git" ...
error: build error: fatal: unable to access 'https://github.com/openshift/ruby-ex.git/': Failed connect to github.com:443; No route to host

please help me if any one has faced this same issue.

**Comment by coreydaley** [comment]
Are you using 'oc cluster up' or building from source?
You may need to try flushing iptables.
It would also be a good idea to use a newer version of OpenShift, 1.5 is fairly old at this point.

**Comment by kumarranja** [comment]
I am building from source.
I tried with OpenShift 1.6 also, but there also I got the same error.

**Comment by bparees** [comment]
please open this issue against origin, it's a networking configuration problem in your cluster/hosts.
